# This is a basic workflow to help you get started with Actions

name: Copy file1 to file2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copy-file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/workflows@v2

      # Runs a set of commands using the runners shell
      - name: Copy file1 to file2
        run: |
         cp file1 file2
         git add file2
         git commit -m "Copy contents of file1 to file2"
         git push
