name: Copy File 1 to File 2

on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy file
      run: |
        cp file1.txt file2.txt
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Copy file1.txt to file2.txt"
        git push
